# Site
name: 'Gerald Haslhofer'
description: 'Gerald Haslhofer blog'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'website'
email: 'haslhofer@outlook.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    gerald:
      name:           Gerald Haslhofer
      site:           https://www.linkedin.com/in/gerald-haslhofer-57582a/
      avatar:         assets/images/gerhas.jpg
      bio:            "Hi, I am Gerald, the author of this blog. I hope you like it!"
      email:          haslhofer@outlook.com
      twitter:        https://twitter.com/atgerhas

    
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: gerald
      avatar: assets/images/gerhas.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]